# Generated by Django 3.2.5 on 2021-11-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='finished',
        ),
    ]
